name: Java CI

#aca definimos las situaciones en las que se ejecutara el pipeline
on: [push]
  #pull_request:
   # branches:
    #  - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      #chequeamos el repo
      - name: Chequear repositorio
        uses: actions/checkout@v4.1.7          

      #preparamos el entorno para java
      - name: Set up JDK 11
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '11'
          distribution: 'temurin'

      #Build with Maven
      - name: construir con maven
        run: mvn -B package --file pom.xml

      #Verificamos el formato del codigo punto 3.d
      - name: vericar el formato del codigo
        run: mvn spotless:check
        #continue-on-error: false

      #verico que cumpla con el linter de java punto 3.c
      - name: Ejecutar el linter de Maven
        run: mvn checkstyle:check



      #correr los test unitarios punto 3.a
      - name: Correr tests unitarios
        run: mvn test

      #no tenemos pruebas de integracion punto 3.b
