name: Java CI

# Definimos cuándo se ejecutará el pipeline
on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      # Chequear el repositorio
      - name: Chequear repositorio
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0  # Trae todo el historial del repo para asegurar que esté completo

      # Preparar entorno para Java
      - name: Set up JDK 11
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '11'
          distribution: 'temurin'

      # Compilar el proyecto con Maven
      - name: Construir con Maven
        run: mvn -B package --file pom.xml

      # Correr tests unitarios
      - name: Correr tests unitarios
        run: mvn test

      # Correr pruebas de integración (Failsafe) punto 3.b
      - name: Correr pruebas de integración
        run: mvn failsafe:integration-test failsafe:verify

      # Verificar que el código sigue las buenas prácticas (linter)
      - name: Ejecutar el linter de Maven
        run: mvn checkstyle:check

      # Verificar el formato del código
      - name: Verificar el formato del código
        run: mvn spotless:check
