name: Java CI/CD Pipeline

# Definimos cuándo se ejecutará el pipeline (al hacer PR a main, develop o staging)
on:
  pull_request:
    branches:
      - main
      - develop
      - staging

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Chequear el repositorio
      - name: Chequear el repositorio
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0  # Asegura que el historial completo del repo esté disponible

      # Configurar el entorno Java
      - name: Configurar JDK 11
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '11'
          distribution: 'temurin'

      # Compilar el proyecto con Maven
      - name: Construir el proyecto con Maven
        run: mvn -B package --file pom.xml

      # Correr pruebas unitarias
      - name: Correr pruebas unitarias
        run: mvn test

      # Correr pruebas de integración (Failsafe)
      - name: Correr pruebas de integración
        run: mvn failsafe:integration-test failsafe:verify

      # Verificar el estilo de código con Checkstyle
      - name: Ejecutar el linter de Maven
        run: mvn checkstyle:check

      # Verificar el formato del código con Spotless
      - name: Verificar el formato del código
        run: mvn spotless:check
